### ISSUE TITLE
Reorganazing the branches

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF-mediawiki-themes#22]
With this system going... we may end up having tons of branches which is like 90% of them being useless... I suggest team to consider branching into;

* curve2_latest (rename the master)
* curve2_lts^
* curve_latest (rename v1.4)
* curve_lts^
* development**

^ use this when latest version has difference compared to lts version -make sure to warn users about it-
**hopefully at certain point we mark curve as final and leave it to its grave.

**Comment by jdarwood007** [comment]
I would rather have the branches match the MW version they support.  Then inside that branch their should be a folder for each skin supported (curve or curve2).

**Comment by XinYenFon** [comment]
that will over-populate the repo as well, we don't have to serve users old code here... Releases should be @ SMorg but development activities should stay as clean as possible, imo.

**Comment by SychO9** [comment]
what's the _lts branches for ? I don't get it, I think two branches `curve` and `curve2` would be better.

**Comment by XinYenFon** [comment]
yea in theory 2 is enough but things get weird once LTS release and Latest has different structure(s) for theming, then you can't push fixes for LTS if you keep it 2 branches, unless the plan is literally keeping it working. Then yea curve/2 2 branches is more than enough.
